name: Lint and vet Go code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.go"

jobs:
  build:
    name: staticcheck
    runs-on: ubuntu-latest
    steps:
      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Install Go on the VM running the action.
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: "=1.21.3"

      - name: Perform staticcheck on codebase
        uses: dominikh/staticcheck-action@fe1dd0c3658873b46f8c9bb3291096a617310ca6 # v1.3.1
        with:
          install-go: false

      - name: Install gofumpt
        run: |
          go install mvdan.cc/gofumpt@latest

      - name: Run gofumpt command
        run: |
          gofumpt -l -d ./

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ec5d18412c0aeab7936cb16880d708ba2a64e1ae # v6.2.0
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

